version: '3.7'
services:
  angular-front:
#    image: ghcr.io/studadvice/studadvice_backoffice:latest
    image: backoffice:latest
    container_name: angular-front
    ports:
      - "4200:80"
      - "443:443"
    restart: always
