name: Deploy to OVH VPS

on:
  workflow_run:
    workflows: [ "Build to Azure VPS" ]
    types:
      - completed
  workflow_dispatch:

jobs:
  deploy:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: SSH and Deploy on VPS
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            echo ${{ secrets.STUDADVICE_BACK_TOKEN }} | sudo docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin
            echo ${{ secrets.PASSWORD }} | sudo docker pull ghcr.io/${{ github.repository_owner }}/studadvice_backoffice:latest
            echo ${{ secrets.PASSWORD }} | sudo docker stack deploy --compose-file docker-compose.yml studadvice
            echo ${{ secrets.PASSWORD }} | sudo docker service update --image ghcr.io/studadvice/studadvice_backoffice --force studadvice_studadvice-backoffice
