name: Deploy to Azure VPS

on:
  workflow_run:
    workflows: [ "Build to Azure VPS" ]
    types:
      - completed
  workflow_dispatch:

jobs:
  deploy:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # make sure to connect github registry to vps
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: SSH and Deploy on VPS
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            sudo docker pull ghcr.io/${{ github.repository_owner }}/studadvice_backoffice:latest
            sudo docker stack deploy --compose-file docker-compose.yml studadvice --with-registry-auth
            sudo docker service update --image ghcr.io/studadvice/studadvice_backoffice --force studadvice_studadvice-backoffice