name: Deploy to Azure VPS

on:
  workflow_dispatch:
jobs:
  deploy:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get latest release
        id: get_release
        uses: actions/github-script@v5
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        with:
          script: |
            console.log(context.repo);
            const repo = context.repo;
            const release = await github.rest.repos.getLatestRelease({
              owner: repo.owner,
              repo: repo.repo
            });
            core.setOutput('tag_name', release.data.tag_name);

      - name: Download artifact from latest release
        run: |
          curl -L -H 'Authorization: token ${{ secrets.PERSONAL_ACCESS_TOKEN }}' -o build.zip https://github.com/${{ github.repository }}/releases/download/${{ steps.get_release.outputs.tag_name }}/dist.zip

      - name: Extract build archive
        run: unzip build.zip -d dist/

      - name: Create deployment directory on server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            mkdir -p /home/azureuser/deploy

      - name: Deploy to Azure VPS
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }}
          source: "dist/*"
          target: "/home/azureuser/deploy"

      - name: Move files to web directory and restart Nginx
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            sudo rsync -av --delete /home/azureuser/deploy/dist/backoffice /var/www/html/
            sudo systemctl restart nginx